version: "3.6"
services:
  app:
    restart: always
    build: .
    links:
      - postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_NAME: nlp
  postgres:
    image: postgres:13
    restart: always
    ports:
    - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nlp
      PGDATA: /postgresql/data/pgdata
    volumes:
    - ./dump:/docker-entrypoint-initdb.d

volumes:
  dump:
